config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  constraints(AdminConstraint.new) do
    resources :users, only: %i[index show destroy]

    scope :event do
      resources :types
    end

    resources :events
    get '/events', to: 'events#index', as: :admin_home
  end

  # Routes for users & presenters
  get '/events', to: 'pages#event', as: :user_home
  get '/events/:id', to: 'pages#show', as: :user_event

  post '/events/:event_id/comments', to: 'comments#create', as: :comments
  get '/events/:event_id/comments/new', to: 'comments#new', as: :new_comment
  delete '/events/:event_id/comments/:id', to: 'comments#destroy', as: :comment
  get '/events/:event_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  patch '/events/:event_id/comments/:id', to: 'comments#update', as: :update_comment

  get '/events/:id/edit', to: 'events#edit_material'
  patch '/events/:id', to: 'events#update_material'
  delete '/events/:id/material/:material_id', to: 'events#destroy_material', as: :delete_material

  resources :events, only: %i[index] do
    resources :participants, only: %i[new create destroy]
  end

  get '/events/all/status', to: 'pages#filter_event', as: :event_filter
  get '/user/profile/:id', to: 'users#show', as: :user_profile
end

app/views/layouts/shared/_admin_sidebar.html.erb
<div
  class="d-flex flex-column flex-shrink-0 p-3 bg-white border-top border rounded m-2 my-3"
  style="min-height: 90vh; width: 100%; position: sticky; top: 8vh;">
  <%= image_tag "logo/Bajra-logo.png", class: "img-fluid" %>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto mb-5">
    <li class="nav-item">
      <%= link_to root_path, class: "nav-link link-dark" do %>
        <i class="fa-solid fa-house bi me-2"></i>
        Home
      <% end %>
    </li>
    <li>
      <a href="#" class="nav-link link-dark text-nowrap">
        <i class="fa-solid fa-gauge bi me-2"></i>
        Dashboard
      </a>
    </li>
    <hr>
    <li>
      <%= link_to events_path , class: "nav-link link-dark" do %>
        <i class="fa-solid fa-calendar-days bi me-2"></i>
        Event
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to types_path , class: "nav-link link-dark" do %>
        <i class="fa-solid fa-table-cells-large bi me-2"></i>
        Event Categories
      <% end %>
    </li>
    <li>
      <%= link_to users_path, class: "nav-link link-dark" do %>
        <i class="fa-solid fa-user bi me-2"></i>
        Users
      <% end %>
    </li>
    <li>
      <a href="#" class="nav-link link-dark">
        <i class="fa-solid fa-gear bi me-2"></i>
        Setting
      </a>
    </li>
  </ul>
  <hr class="mt-5">
  <ul class=" nav d-flex flex-row justify-content-around ">
    <li class="h4">
      <a href="#" class="link-dark"><i class="fa-brands fa-facebook"></i></a>
    </li>
    <li class="h4">
      <a href="#" class="link-dark"><i class="fa-brands fa-instagram"></i></a>
    </li>
    <li class="h4">
      <a href="#" class="link-dark"><i class="fa-brands fa-linkedin"></i></a>
    </li>
    <li class="h4">
      <a href="#" class="link-dark"><i class="fa-brands fa-youtube"></i></a>
    </li>
  </ul>
</div>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div 
    class="flash__message bg-dark text-white p-3 rounded my-2 position-fixed bottom-0 right-0 z-3"
    data-controller="removals"
    data-action="animationend->removals#remove">
    <p class="fw-normal text-nowrap"><span class="rounded-pill p-1 px-2 bg-success text-white"><i class="fa-solid fa-check fa-sm"></i></span>&ensp;<%= message %></p>
  </div>
<% end %>

app/views/layouts/shared/_user_nav.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white px-3 mb-3">
    <div class="container-fluid">
      <a class="navbar-brand bajra-text-primary" href="/">LLMS</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarText"
        aria-controls="navbarText"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <div class="dropdown d-flex">
              <div class="nav-item dropdown">
                <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <% if !current_user.avatar.attached? %>
                    <span
                  class="
                    me-2
                    p-2
                    rounded-pill
                    align-self-center
                    h6
                  "
                  style="background-color: #FBDCD3; color: #BE263B;"
                >
                      <%= current_user.first_name.capitalize()[0] %><%= current_user.last_name.capitalize()[0] %></span>
                  <% else %>
                    <%= image_tag url_for(current_user.avatar), class: "rounded-pill", style: "width: 35px; height: 35px; object-fit: cover;" %>
                  <% end %>
                  <%= current_user.username %>
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to user_profile_path(current_user), class: "dropdown-item" do %>
                      <i class="fa-solid fa-id-badge bi me-2"></i>
                      Profile
                    <% end %>
                  </li>
                  <li><button class="dropdown-item" type="button"><i class="fa-solid fa-list me-2"></i>Attended Events</button></li>
                  <li><button class="dropdown-item" type="button"><i class="fa-solid fa-calendar-check bi me-2"></i>My Events</button></li>
                </ul>
              </div>
              <%= button_to destroy_user_session_path, class: "btn btn-default display-2", method: :delete do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                Logout
              <% end %>
            </div>
          <% else %>
            <%= link_to "login", new_user_session_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>