config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  constraints(AdminConstraint.new) do
    resources :users, only: %i[index show destroy]

    scope :event do
      resources :types
    end

    resources :events
    get '/events', to: 'events#index', as: :admin_home
  end

  # Routes for users & presenters
  get '/events', to: 'pages#event', as: :user_home
  get '/events/:id', to: 'pages#show', as: :user_event

  post '/events/:event_id/comments', to: 'comments#create', as: :comments
  get '/events/:event_id/comments/new', to: 'comments#new', as: :new_comment
  delete '/events/:event_id/comments/:id', to: 'comments#destroy', as: :comment
  get '/events/:event_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  patch '/events/:event_id/comments/:id', to: 'comments#update', as: :update_comment

  get '/events/:id/edit', to: 'events#edit_material'
  patch '/events/:id', to: 'events#update_material'
  delete '/events/:id/material/:material_id', to: 'events#destroy_material', as: :delete_material

  resources :events, only: %i[index] do
    resources :participants, only: %i[new create destroy]
  end

  get '/events/all/status', to: 'pages#filter_event', as: :event_filter
  get '/user/profile/:id', to: 'users#show', as: :user_profile
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :event
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  # Validations
  validates :user, presence: true
  validates :content, presence: true, length: { minimum: 1 }
  validates :event, presence: true

  broadcasts_to ->(comment) { [comment.event, 'comments'] }, inserts_by: :prepend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: %i[create new destroy edit update]
  before_action :set_comment, only: %i[destroy edit update]

  def new
    @comment = @event.comments.new
  end

  def create
    @comment = @event.comments.build(comment_params.merge(user_id: current_user.id))
    if @comment.save

      respond_to do |format|
        @current_user = current_user
        
        format.html { redirect_to user_event_path(@event), notice: 'Record successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        @current_user = current_user

        redirect_to user_event_path(@event), notice: 'Record updated successfully.'
        format.turbo_stream
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @comment.destroy
    @current_user = current_user

    respond_to do |format|
      format.html { redirect_to user_event_path(@event), notice: 'Record deleted successfully.' }
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag "comment_#{comment.id}" do %>
  <div class="commented-section mt-2 border p-3 rounded">
    <div
      class="
        d-flex
        flex-row
        align-items-center
        justify-content-between
        commented-user
      "
    >
      <div class="commenter-details d-flex align-items-end">
        <% if current_user.avatar.attached? %>
          <%= image_tag (url_for(comment.user.avatar)),
        style: "width: 38px; height: 38px; object-fit: cover;",
        class: "img-fluid img-responsive rounded-circle me-2" %>
        <% end %>
        <h5 class="text-primary fw-bold ms-2">
          <%= comment.user.username %></h5>
      </div>
      <span class="mb-1"><%= time_ago_in_words(comment.created_at) %>
        ago</span></div>
    <div class="comment-text-sm p-3"><span><%= comment.content %></span></div>
    <div class="reply-section">
      <div class="d-flex flex-row align-items-center voting-icons">
        <div class="" id="accordionPanelsStayOpenExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
              <button class="btn btn-sm btn-default"><i class="fa-solid fa-reply bi me-2"></i>Reply</button>
              <% if comment.replies.count > 0 %>
                <button
                  class="btn btn-sm bt-primary"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#panelsStayOpen-<%= comment.id %>"
                  aria-expanded="true"
                  aria-controls="panelsStayOpen-collapseOne"
                >
                  <i class="fa-solid fa-comments bi me-2"></i>
                  Replies
                </button>
              <% end %>
              <% if current_user == comment.user %>
                <%= link_to comment_path(comment.event_id, comment.id), class: "btn btn-sm btn-default", data: { "turbo-method": :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-trash bi me-2"></i>Remove
                <% end %>
                <%= link_to edit_comment_path(comment.event_id, comment.id), class: "btn btn-sm btn-default" do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                  Edit
                <% end %>
              <% end %>
            </h2>
            <div
              id="panelsStayOpen-<%= comment.id %>"
              class="accordion-collapse collapse"
              aria-labelledby="panelsStayOpen-headingOne"
            >
              <div class="accordion-body mb-2 ms-5">
                <%= render partial: "/comments/replies", locals: { reply: comment.replies } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="d-flex flex-row add-comment-section mt-4 mb-4 w-100">
  <% if current_user.avatar.attached? %>
    <%= image_tag (url_for(current_user.avatar)),
  style: "width: 38px; height: 38px; object-fit: cover;",
  class: "img-fluid img-responsive rounded-circle me-2" %>
  <% end %>
  <% if @comment.persisted? %>
    <%= form_with(model: @comment, class: 'd-flex w-100', method: @comment.persisted? ? :patch : :post, url: @comment.persisted? ? comment_url(@event.id, @comment) : update_comment_url(@event.id)) do |form| %>
      <div class="form-group w-100">
        <%= form.text_field :content, class: "form-control", placeholder: "Add Comment" %>
        <% @comment.errors.full_messages_for(:content).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.submit "Comment", type: "submit", class: "btn btn-primary ms-2" %>
      </div>
    <% end %>
  <% else %>
    <%= form_with(model: @comment, url: comments_url(@event.id), class: 'd-flex w-100') do |form| %>
      <div class="form-group w-100">
        <%= form.text_field :content, class: "form-control", placeholder: "Add Comment" %>
        <% @comment.errors.full_messages_for(:content).each do |message| %>
          <div class="text-danger"><%= message %></div>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.submit "Comment", type: "submit", class: "btn btn-primary ms-2" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/_replies.html.erb
<% reply.each do |reply| %>
  <turbo-frame id="comment_<%= reply.id %>_<%= reply.parent_id %>">
    <div class="card my-2 reply-width">
      <div class="card-body">
        <div class="d-flex flex-start">
          <%= image_tag (url_for(reply.user.avatar)),
          style: "width: 40px; height: 40px; object-fit: cover;",
          class: "rounded-circle shadow-1-strong me-3" %>
          <div class="w-100">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h6 class="text-primary fw-bold mb-0">
                <%= reply.user.username %>
                <span class="text-dark ms-2"><%= reply.content %></span>
              </h6>
              <p class="mb-0"><%= time_ago_in_words(reply.created_at) %>
                ago</p>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <p class="small mb-0" style="color: #aaa;">
                <% if current_user.id == reply.user_id %>
                  <%= link_to comment_path(reply.event_id, reply.id), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?"} do %>
                    Remove
                  <% end %>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </turbo-frame>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments",
                     partial: "comments/comment",
                     locals: {
                       comment: @comment,
                       current_user: @current_user
                     } %>
<%= turbo_stream.update Comment.new, "" %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>
<%= turbo_stream.remove "comment_#{@comment.id}_#{@comment.parent_id}" %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "comment_#{@comment.id}" do %>
  <%= render "form", comment: @comment %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render partial: "comments/form", comment: @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace @comment %>