config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  constraints(AdminConstraint.new) do
    resources :users, only: %i[index show destroy]

    scope :event do
      resources :types
    end

    resources :events
    get '/events', to: 'events#index', as: :admin_home
  end

  # Routes for users & presenters
  get '/events', to: 'pages#event', as: :user_home
  get '/events/:id', to: 'pages#show', as: :user_event

  post '/events/:event_id/comments', to: 'comments#create', as: :comments
  get '/events/:event_id/comments/new', to: 'comments#new', as: :new_comment
  delete '/events/:event_id/comments/:id', to: 'comments#destroy', as: :comment
  get '/events/:event_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  patch '/events/:event_id/comments/:id', to: 'comments#update', as: :update_comment

  get '/events/:id/edit', to: 'events#edit_material'
  patch '/events/:id', to: 'events#update_material'
  delete '/events/:id/material/:material_id', to: 'events#destroy_material', as: :delete_material

  resources :events, only: %i[index] do
    resources :participants, only: %i[new create destroy]
  end

  get '/events/all/status', to: 'pages#filter_event', as: :event_filter
  get '/user/profile/:id', to: 'users#show', as: :user_profile
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[show edit update destroy]

  def index
    @pagy, @types = pagy(Type.all.order(created_at: :desc))
  end

  def show; end

  def new
    @type = Type.new
  end

  def create
    @type = Type.create(type_params)

    if @type.save
      respond_to do |format|
        format.html { redirect_to types_path, notice: 'Record successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Record successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @type.update(type_params)
        redirect_to types_path, notice: 'Record updated successfully.'
        format.turbo_stream { flash.now[:notice] = 'Record updated successfully.' }
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    if @type.events.empty?
      @type.destroy
      respond_to do |format|
        format.html { redirect_to types_path, notice: 'Record deleted successfully.' }
        format.turbo_stream { flash.now[:notice] = 'Record deleted successfully.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to types_path, alert: 'Record is still referenced by events and cannot be deleted.' }
        format.turbo_stream { flash.now[:alert] = 'Record is still referenced by events and cannot be deleted.' }
      end
    end
  end

  private

  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:name)
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with model: @type do |form| %>
  <div>
    <% if type.errors.any? %>
      <div class="error-message text-danger">
        <%= type.errors.full_messages.to_sentence.capitalize %>
      </div>
    <% end %>
  </div>
  <div class="row row align-items-end border p-5">
    <div class="col">
      <%= form.label :name, :class => "form-label"%>
      <%= form.text_field :name, :autofocus => true, :class => "form-control" %>
    </div>
    <div class="col-3 d-flex justify-content-around">
      <%= button_to "Create", type: "submit",  class: "btn btn-success" do %>
        Create
      <% end %>
      <%= link_to " Cancel", types_path, class: "btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/types/_type.html.erb
<%= turbo_frame_tag "type_#{type.id}" do %>
  <div class="quote border d-flex justify-content-between align-items-center my-3 p-1">
    <h6 class= "col-lg-10 col-md-8 col-sm-6 ps-5">
      <span class="fw-bold me-2"><%= type.id %>.</span>
      <%= type.name%>
    </h6>
    <div class="
        quote__actions
        col-lg-2
        col-md-4
        col-sm-6
        my-sm-4
        d-flex
        justify-content-around
      "
    >
      <%= button_to type_path(type),
      method: :delete,
      form: {
        data: {
          turbo_frame: "_top"
        }
      },
      class: "btn btn-sm btn-secondary text-white text-nowrap " do %>
        <i class="fa-solid fa-trash bi me-2"></i>
        Delete
      <% end %>
      <%= link_to edit_type_path(type),
      class: "btn btn-sm btn-outline-primary text-nowrap ",
      data: {
        turbo_frame: type
      } do %>
        <i class="fa-solid fa-pen bi me-2"></i>
        Edit
      <% end %>
    </div>
  </div>
<% end %>

app/views/types/create.turbo_stream.erb
<%= turbo_stream.prepend "types", partial: "types/type", locals: { type: @type } %>
<%= turbo_stream.update Type.new, "" %>
<%= turbo_stream.prepend "flash", partial: "layouts/shared/flash" %>

app/views/types/destroy.turbo_stream.erb
<%= turbo_stream.remove @type %>
<%= turbo_stream.prepend "flash", partial: "layouts/shared/flash" %>

app/views/types/edit.html.erb
 <%= link_to sanitize("&larr; Back to quote"), types_path(@type) %>
<div class="header">
  <h1>Edit Type</h1>
</div>
<%= turbo_frame_tag "type_#{@type.id}" do %>
  <%= render "form", type: @type %>
<% end %>

app/views/types/index.html.erb
<div class="container-fluid bg-white rounded border">
  <div id="flash" class="flash">
    <%= render "layouts/shared/flash" %>
  </div>
  <div class="header d-flex justify-content-between align-items-center p-2">
    <h2>Event Types List</h2>
    <diV>
      <%= link_to new_type_path, class: "btn btn-sm btn-primary", data: {turbo_frame: dom_id(Type.new)} do %>
        <i class="fa-solid fa-plus bi me-2"></i>
        New Event Type
      <% end%>
    </diV>
  </div>
  <hr class="text-muted">
  <%= turbo_frame_tag Type.new %>
  <%= turbo_frame_tag "types" do %>
    <%= render @types %>
  <% end %>
  <nav aria-label="Page navigation example position-absolute bottom-0">
    <ul class="pagination justify-content-center">
      <li class="page-item <%= 'disabled' if @pagy.prev.nil? %>">
        <%= if @pagy.prev
            link_to "Previous", pagy_url_for(@pagy, @pagy.prev), class: "page-link"
          end %>
      </li>
      <% @pagy.series.each do |item| %>
        <li class="page-item <%= 'active' if item == @pagy.page %>">
          <%= link_to item, pagy_url_for(@pagy, item), class: "page-link" %>
        </li>
      <% end %>
      <li class="page-item <%= 'disabled' if @pagy.next.nil? %>">
        <%= if @pagy.next
            link_to "Next", pagy_url_for(@pagy, @pagy.next), class: "page-link"
          end %>
      </li>
    </ul>
  </nav>
</div>

app/views/types/new.html.erb
<main class="container">
  <div class="mt-2">
    <%= link_to sanitize("&larr; Back to quotes"), types_path %>
  </div>
  <div class="header mt-2">
    <h1>New Event Type</h1>
  </div>
  <%= turbo_frame_tag @type do %>
    <%= render "form", type: @type %>
  <% end %>
</main>

app/views/types/update.turbo_stream.erb
<%= turbo_stream.replace @type %>
<%= turbo_stream.prepend "flash", partial: "layouts/shared/flash" %>