config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  constraints(AdminConstraint.new) do
    resources :users, only: %i[index show destroy]

    scope :event do
      resources :types
    end

    resources :events
    get '/events', to: 'events#index', as: :admin_home
  end

  # Routes for users & presenters
  get '/events', to: 'pages#event', as: :user_home
  get '/events/:id', to: 'pages#show', as: :user_event

  post '/events/:event_id/comments', to: 'comments#create', as: :comments
  get '/events/:event_id/comments/new', to: 'comments#new', as: :new_comment
  delete '/events/:event_id/comments/:id', to: 'comments#destroy', as: :comment
  get '/events/:event_id/comments/:id/edit', to: 'comments#edit', as: :edit_comment
  patch '/events/:event_id/comments/:id', to: 'comments#update', as: :update_comment

  get '/events/:id/edit', to: 'events#edit_material'
  patch '/events/:id', to: 'events#update_material'
  delete '/events/:id/material/:material_id', to: 'events#destroy_material', as: :delete_material

  resources :events, only: %i[index] do
    resources :participants, only: %i[new create destroy]
  end

  get '/events/all/status', to: 'pages#filter_event', as: :event_filter
  get '/user/profile/:id', to: 'users#show', as: :user_profile
end

app/models/event.rb
class Event < ApplicationRecord
  # Associations
  belongs_to :type
  has_one_attached :cover_picture
  has_rich_text :content
  has_many :comments, dependent: :destroy
  has_many_attached :materials
  has_many :participants, dependent: :destroy
  has_many :attendees, through: :participants, source: :user, dependent: :destroy

  enum status: %i[upcoming finished cancled
                  hold]
  enum visibility: %i[event_public event_presenter event_private]

  # Validation
  validates_associated :cover_picture
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :status, presence: true
  validates :visibility, presence: true
  validates :location, presence: true, length: { maximum: 255 }
  validates :type, presence: true
  validates :cover_picture, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy edit_material update_material destroy_material]
  before_action :is_presenter, only: %i[edit_material update_material]

  def index
    @pagy, @events = pagy(Event.all.order(created_at: :desc))
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.where(parent_id: nil)
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)

    if @event.save
      respond_to do |format|
        format.html { redirect_to events_path, notice: 'Record successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'Record updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Record deleted successfully.'
  end

  def edit_material
    render :edit_material
  end

  def update_material
    respond_to do |format|
      if @event.update(event_params)
        redirect_to user_event_path(@event), notice: 'Record updated successfully.'
        format.turbo_stream
      else
        render :edit_material, status: :unprocessable_entity
      end
    end
  end

  def destroy_material
    return unless current_user.admin? || current_user.presenter?

    @material = @event.materials.find_by(id: params[:material_id])
    @material.purge

    respond_to do |format|
      # redirect_to user_event_path(@event), notice: 'Record deleted successfully.'
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove("event_material_#{@material.id}")
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :time, :duration, :status, :visibility, :location,
                                  :type_id, :cover_picture, :content, materials: [])
  end

  def is_presenter
    redirect_to root_path unless current_user.presenter?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit.html.erb
<div class="d-flex justify-content-between align-items-center rounded bg-white p-3 mb-3">
  <h2 class="bajra-text-primary">New Event</h2>
  <div class="d-flex">
    <%= link_to events_path, class: "btn btn-sm btn-primary me-2" do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
      Go Back
    <% end %>
  </div>
</div>
<%= render "form" %>

app/views/events/_event.html.erb
<div class="col-12 bg-white">
  <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col p-4 d-flex flex-column position-static">
      <strong class="d-inline-block mb-2 text-primary"><i class="fa-solid fa-people-group me-2 text-dark"></i><%= event.type.name %></strong>
      <h3 class="mb-0"><%= event.title%></h3>
      <div class="my-1 text-muted d-flex">
        <p><i class="fa-solid fa-calendar-days me-2"></i><%= event.date.strftime("%A, %d %b %Y") %></p>
        <p class="ms-3"><i class="fa-solid fa-clock fa-beat me-2"></i><%= event.time.strftime("%I:%M %p") %></p>
        <p class="ms-3"><i class="fa-solid fa-hourglass-start me-2"></i><%= event.duration %> hrs</p>
      </div>
      <div class="mb-1 text-muted"> <span class="badge bg-success text-white"><%= event.status.capitalize %></span> </div>
      <p class="card-text mb-auto lead"> <%= truncate(event.description, length: 250) %> </p>
      <div class="mb-1 text-muted"><i class="fa-solid fa-location-dot me-2"></i><%= event.location %></div>
      <div class="my-2">
        <%= link_to event_path(event), class: 'btn btn-primary btn-sm' do%>
          <i class="fa-solid fa-eye fa-bounce me-2"></i>
          View
        <% end %>
      </div>
    </div>
    <div class="col-auto d-none d-lg-block">
      <%= image_tag (url_for(event.cover_picture)),
      style: "width: 600px; height: 400px; object-fit: cover; object-position: center top",
      class: "img-fluid" %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="bg-white p-3">
  <%= form_with model: @event do |form| %>
    <div class="form-group my-2">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, :class => "form-control" %>
      <% @event.errors.full_messages_for(:title).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="mt-5 d-flex flex-sm-column flex-lg-row flex-md-column">
      <div class="w-75 me-5">
        <div class="form-group mb-3">
          <%= form.rich_text_area :content, class: 'form-control customized-min-height' %>
        </div>
        <div class="form-group my-3 d-flex align-items-center">
          <div class="form-group my-2 mb-3 col-4">
            <%= form.label :status, class: 'form-label' %>
            <%= form.collection_select :status, Event.statuses.keys, :to_s, :humanize, {}, { class: 'form-select' } %>
          </div>
          <div class="form-group my-2 mb-3 col-4 ms-2">
            <%= form.label :visibility, class: 'form-label' %>
            <%= form.collection_select :visibility, Event.visibilities.keys, :to_s, :humanize, {}, { class: 'form-select' } %>
          </div>
          <div class="form-group ms-3">
            <%= form.submit class:"btn btn-sm btn-primary mt-4" %>
          </div>
        </div>
      </div>
      <div class=" w-25 event-left-box">
        <div class="form-group my-2 mb-3">
          <%= form.label :description, class: 'form-label' %>
          <%= form.text_area :description, :class => "form-control", style: "height: 10vh;" %>
          <% @event.errors.full_messages_for(:description).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :duration, class: 'form-label' %>
          <%= form.number_field :duration, :class => "form-control" %>
          <div class="text-danger"><%= @event.errors.full_messages_for(:duration)[0] %></div>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :time, class: 'form-label' %>
          <%= form.time_field :time, :class => "form-control w-100" %>
          <% @event.errors.full_messages_for(:time).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :date, class: 'form-label' %>
          <%= form.date_field :date, :class => "form-control" %>
          <% @event.errors.full_messages_for(:date).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :location, class: 'form-label' %>
          <%= form.text_field :location, :class => "form-control" %>
          <% @event.errors.full_messages_for(:location).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label "Targeted Audience", class: 'form-label' %>
          <%= form.collection_select :type_id, Type.all, :id, :name, {}, { class: 'form-select' } %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :cover_picture, class: 'form-label' %>
          <%= form.file_field :cover_picture, :class => "form-control" %>
          <% @event.errors.full_messages_for(:cover_picture).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div class="form-group my-2 mb-3">
          <%= form.label :materials, class: 'form-label' %>
          <%= form.file_field :materials, :class => "form-control", multiple: true %>
          <% if @event.materials.attached? %>
            <% @event.materials.each do |material| %>
              <%= form.hidden_field :materials, multiple: true, value: material.signed_id %>
            <% end %>
            <div>
              <% @event.materials.each do |material| %>
                <p class="mt-2"> <%= material.filename %> </p>
              <% end %>
            </div>
          <% end %>
          <% @event.errors.full_messages_for(:materials).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="d-flex justify-content-between align-items-center rounded bg-white p-3 mb-3">
  <h2 class="bajra-text-primary">New Event</h2>
  <div class="d-flex">
    <%= link_to events_path, class: "btn btn-sm btn-primary me-2" do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
      Go Back
    <% end %>
  </div>
</div>
<%= render "form" %>

app/views/events/edit_material.html.erb
<%= turbo_frame_tag "material_#{@event.id}" do %>
  <div class="bg-white p-3 my-3 rounded">
    <%= form_with model: @event do |form| %>
      <div class="form-group d-flex align-items-end">
        <% @event.materials.each do |material|%>
          <%= form.hidden_field :materials, multiple: true, value: material.signed_id %>
        <% end %>
        <div class="w-100">
          <%= form.label :materials, class: 'form-label'%>
          <%= form.file_field :materials, :class => "form-control", multiple: true%>
          <% @event.errors.full_messages_for(:materials).each do |message| %>
            <div class="text-danger"><%= message %></div>
          <% end %>
        </div>
        <div>
          <%= form.submit class: 'ms-2 btn btn-sm btn-primary mb-1'%>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="d-flex justify-content-between align-items-center rounded bg-white p-3 mb-3">
  <h2 class="bajra-text-primary">Events</h2>
  <div class="d-flex">
    <%= link_to new_event_path, class: "btn btn-sm btn-secondary me-2" do %>
      <i class="fa-solid fa-plus me-2"></i>
      Create
    <% end %>
    <%= link_to root_path, class: "btn btn-sm btn-primary me-2" do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
      Go Back
    <% end %>
  </div>
</div>
<%= render @events %>
<nav aria-label="Page navigation example position-absolute bottom-0">
  <ul class="pagination justify-content-center">
    <li class="page-item <%= 'disabled' if @pagy.prev.nil? %>">
      <%= if @pagy.prev
            link_to "Previous", pagy_url_for(@pagy, @pagy.prev), class: "page-link"
          end %>
    </li>
    <% @pagy.series.each do |item| %>
      <li class="page-item <%= 'active' if item == @pagy.page %>">
        <%= link_to item, pagy_url_for(@pagy, item), class: "page-link" %>
      </li>
    <% end %>
    <li class="page-item <%= 'disabled' if @pagy.next.nil? %>">
      <%= if @pagy.next
            link_to "Next", pagy_url_for(@pagy, @pagy.next), class: "page-link"
          end %>
    </li>
  </ul>
</nav>

app/views/events/new.html.erb
<div class="d-flex justify-content-between align-items-center rounded bg-white p-3 mb-3">
  <h2 class="bajra-text-primary">New Event</h2>
  <div class="d-flex">
    <%= link_to events_path, class: "btn btn-sm btn-primary me-2" do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
      Go Back
    <% end %>
  </div>
</div>
<%= render "form" %>

app/views/events/show.html.erb
<div class="d-flex justify-content-between align-items-center rounded bg-white p-3">
  <h2 class="bajra-text-primary">Event Details</h2>
  <div class="d-flex">
    <%= link_to new_event_participant_path(@event), class: "btn btn-sm btn-primary me-2", data: {turbo_frame: dom_id(Participant.new)} do %>
      <i class="fa-solid fa-plus me-2"></i>
      Add Presenter
    <% end %>
    <%= button_to event_path(@event), method: :delete, class: "btn btn-sm btn-danger me-2" do %>
      <i class="fa-solid fa-trash me-2"></i>
      Delete
    <% end %>
    <%= link_to edit_event_path(@event), class: "btn btn-sm btn-secondary me-2" do %>
      <i class="fa-solid fa-pen me-2"></i>
      Edit
    <% end %>
    <%= link_to events_path, class: "btn btn-sm btn-primary me-2" do %>
      <i class="fa-solid fa-arrow-left me-2"></i>
      Go Back
    <% end %>
  </div>
</div>
<%= turbo_frame_tag Participant.new %>
<div class="bg-white  my-3 p-3 d-flex">
  <div>
    <div class="w-75 m-auto">
      <div class="my-1 text-muted d-flex mb-3">
        <p><i class="fa-solid fa-calendar-days me-2"></i><%= @event.date.strftime("%A, %d %b %Y") %></p>
        <p class="ms-3"><i class="fa-solid fa-clock fa-beat me-2"></i><%= @event.time.strftime("%I:%M %p") %></p>
        <p class="ms-3"><i class="fa-solid fa-hourglass-start me-2"></i><%= @event.duration %> hrs</p>
      </div>
      <h2 class="my-3"><%= @event.title %></h2>
      <p class="lead my-2"><%= @event.description %></p>
      <div class="mb-1 text-muted">
        <span class="badge bg-success text-white"><%= @event.status.capitalize %></span>
        <% if @event.visibility == 'event_public' %>
          <span class="badge bg-primary text-white"><i class="fa-solid fa-lock-open me-2"></i>Public</span>
        <% elsif @event.visibility == 'event_private' %>
          <span class="badge bg-primary text-white"><i class="fa-solid fa-lock me-2"></i>Private</span>
        <% elsif @event.visibility == 'event_presenter' %>
          <span class="badge bg-primary text-white"><i class="fa-solid fa-users me-2"></i>Presenter</span>
        <% end %>
      </div>
      <div class="mb-1 fw-bold my-2"><i class="fa-solid fa-location-dot me-2"></i><%= @event.location %></div>
      <%= image_tag url_for(@event.cover_picture), class: 'img-fluid w-100 my-3' %>
      <div class="my-2 lead"><%= @event.content %></div>
      <%# Materials list %>
      <div class="my-3">
        <%= turbo_frame_tag "event_materials" do %>
          <ul class="list-group">
            <% @event.materials.each do |material| %>
              <%= turbo_frame_tag "event_material_#{material.id}" do %>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <%= material.filename %>
                  <div class="col-4 button-list">
                    <%= link_to rails_blob_path(material, disposition: 'attachment'), class: 'btn btn-sm btn-primary mb-1' do %>
                      <i class="fa-solid fa-download bi me-2"></i>
                      Download
                    <% end %>
                    <%= link_to rails_blob_path(material, disposition: 'preview'), class: 'ms-2 btn btn-sm btn-primary mb-1' do %>
                      <i class="fa-solid fa-expand bi me-2"></i>
                      View
                    <% end %>
                    <%# Delte material %>
                    <% if current_user.admin? || current_user.presenter? %>
                      <%= link_to delete_material_path(@event.id, material.id), class: "btn btn-sm btn-default bajra-text-primary me-2", data: { "turbo-method": :delete, confirm: 'Are you sure?' } do %>
                        <i class="fa-solid fa-trash"></i>
                      <% end %>
                    <% end %>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
    <section class="mt-5 mb-5 w-75 m-auto">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Comments</h2>
        <%= link_to "Comment",
        new_comment_path(@event),
        data: {
          turbo_frame: dom_id(Comment.new)
        } %>
      </div>
      <hr>
      <%= turbo_frame_tag Comment.new %>
      <div class="d-flex justify-content-center row">
        <div class="d-flex flex-column col-md-12">
          <div class="coment-bottom bg-white p-2 px-4">
            <% render template: "comments/new" %>
            <%= turbo_frame_tag "comments" do %>
              <%= render @comments %>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>
  <div class="w-25 m-3">
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Participants (<%= @event.attendees.count %>)
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <ul class="list-group list-group-flush">
              <%= turbo_frame_tag "participants" do %>
                <%= render partial: 'pages/shared/participant', local: {attendees: @attendees} %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>